modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="icurrency"
version="${file.jarVersion}"
displayName="iCurrency"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="icurrency.png"
credits="Thanks to Forge Forums, Github Copilot and VikkiVuk!"
authors="VikkiVuk"
description='''
iCurrency is a mod that adds a currency system to Minecraft, using bank accounts and notes.
'''

[[dependencies.icurrency]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.icurrency]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"