modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="mcurrency"
version="1.20.61.0.0"
displayName="MCurrency"
displayURL="https://modrinth.com/project/mcurrency"
logoFile="logo.png"
credits="XMasterWoo for helping with some models and textures"
authors="VikkiVuk"
description="The most realistic banking mod for minecraft."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mcurrency]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.mcurrency]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




[[mixins]]
    config="mixins.mcurrency.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration